# Generated by Django 3.2.8 on 2021-10-29 02:13

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kata name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Kata Slug')),
                ('cw_id', models.CharField(max_length=255, verbose_name='Codewars ID')),
                ('languages', models.CharField(max_length=255, verbose_name='Langauges Used')),
                ('description', models.TextField(verbose_name='Kata Description')),
                ('tags', models.CharField(max_length=255, verbose_name='Kata Tags')),
                ('rank', models.CharField(max_length=255, verbose_name='Kata Rank')),
                ('url', models.URLField(null=True, verbose_name='Kata URL')),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
