# Generated by Django 3.2.9 on 2021-11-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.TextField(verbose_name='Kata name'),
        ),
    ]
